### ISSUE TITLE
In der Vorschau werden Module angezeigt, die für das ausgewählte Template nicht verfügbar sind

### ISSUE THREAD

**Issue by dgrothaus-mc** [FriendsOfREDAXO/module_preview#10]
**Description / Beschreibung**

Die Modulvorschau zeigt Module an, die für das ausgewählte Template nicht verfügbar sein sollten.

**Affected versions / Verwendete Versionen**

<details>
<summary>System report (REDAXO 5.15.1, PHP 8.1.22, MariaDB 10.5.21)</summary>

**Nur relevanter Auszug**

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.15.1     |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 8.1.22                         |
|       OPcache | no                             |
|        Xdebug | yes                            |

| Packages               |            |
| ---------------------: | :--------- |
|         module_preview | 1.3.0      |
|              structure | 2.15.0     |
|      structure/content | 2.15.0     |

</details>

**Reproduktion**

1. Struktur im Backend auswählen.
2. Beliebigen Artikel bearbeiten
3. In der URL ist zu diesem Zeitpunkt der GET Parameter `ctype` noch nicht gesetzt.
4. Die Modulvorschau prüft gegen cType **0**, statt gegen cType **1**.
5. Die Methode `rex_template::hasModule()` des structure Addons gibt immer _verfügbar_ zurück für unbekannte cTypes.
6. Es werden Module angezeigt, die für das Template nicht verfügbar sind.

**Comment by eaCe** [comment]
Danke für den Hinweis, werde es am Wochenende checken.

**Comment by eaCe** [comment]
Oder so ;) Danke!

**Comment by dgrothaus-mc** [comment]
Ich hatte nicht damit gerechnet, dass jemand so schnell antwortet, und ich somit kaum Zeit habe den PR aus zu formulieren. 😁

**Comment by eaCe** [comment]
Bis zum neuen Release möchte ich noch die Workflows updaten, das schaffe ich in dieser Woche. Nur nicht direkt
