### ISSUE TITLE
Zuordnung von Screenshots via UI

### ISSUE THREAD

**Issue by alexwenz** [FriendsOfREDAXO/module_preview#3]
Redakteure/Agentur die Möglichkeit geben, ohne FTP-Zugang die Screenshots über die Addon-Oberfläche zuzuordnen.

#WasManAuchMachenKönntIssue ;-)

**Comment by eaCe** [comment]
@alexwenz möchtest du dir die aktuelle Version mal ansehen? Man kann nun in einem weiteren Tab in den Einstellungen die Bilder den Modulen zuordnen (hochladen und löschen).

**Comment by alexwenz** [comment]
Super! Ich schaue es mir schnellstmöglich an!

**Comment by eaCe** [comment]
@alexwenz  konntest du es zufällig schon testen?

**Comment by eaCe** [comment]
Ich sehe das es erst ab REDAXO 5.12.0 funktioniert, da ich `symfony/http-foundation` nutze -> https://github.com/redaxo/redaxo/releases/tag/5.12.0
Ich weiß nicht genau ob ich das noch mal umbauen sollte :/
