### ISSUE TITLE
"Block hinzufügen"-Button nicht sichtbar

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/module_preview#4]
Gleich nach Installation des Addons werden die "Block hinzufügen"-Buttons nicht mehr angezeigt.
Diese sind zwar noch da und klickbar, aber visuell nicht mehr sichtbar

Getestet mit Rex 5.12.1

![1](https://user-images.githubusercontent.com/4291047/141063583-68ba0f01-17aa-4392-9f62-1b2e9b5ab601.PNG)

**Comment by eaCe** [comment]
@iceman-fx kannst du mir noch mitteilen welche Addons installiert sind? Ist das in allen Browsern so?
In den Einstellungen kannst du die Klassische Ansicht aktiviern, dann sollte es wieder funktionieren?

**Comment by eaCe** [comment]
@iceman-fx ich denke ich habe das Problem gefunden. Ich werde es testen, einen neuen release erstellen, dann wäre es gut wenn du es vielleicht gegenprüfen könntest.

**Comment by eaCe** [comment]
@iceman-fx gerne testen:
https://github.com/FriendsOfREDAXO/module_preview/releases/tag/1.0.2

Liegt nun auch im installer

**Comment by iceman-fx** [comment]
Gerade getestet.
Klappt jetzt.

Danke.
