### ISSUE TITLE
Darstellung Bilder deaktivieren

### ISSUE THREAD

**Issue by novinet-dsteffen** [FriendsOfREDAXO/module_preview#6]
Ne Option wäre cool, die die Bilderdarstellung komplett deaktiviert.
Es ist einfach moderner und schneller in der modalen Darstellung, selbst wenn keine Bilder vorhanden sind. Und über die Suche geht das mega schnell. Würde damit sozusagen die aktuelle Modulauswahl ersetzen. Bei 40 - 50 Modulen sucht man sich aktuell  nen Wolf ;-)

**Comment by eaCe** [comment]
Vermutlich werde ich die Styles hierzu noch mal etwas überarbeiten.
