### ISSUE TITLE
Bloecks copy & paste integrieren

### ISSUE THREAD

**Issue by novinet-dsteffen** [FriendsOfREDAXO/module_preview#7]
Aktuell funktioniert copy & paste von Bloecks nicht. Könnte man das noch ergänzen?
Vielleicht dann direkt unter der Suche breit ausgeben in einer anderen Farbe?

**Comment by eaCe** [comment]
@novinet-dsteffen gerne die aktuelle Version testen.
Die Module werden nun via Ajax geladen. Das ist zumindest schon mal ein schritt für die Integration von gridblock

**Comment by novinet-git** [comment]
sehr cool!

**Comment by eaCe** [comment]
@novinet-dsteffen konntest du es zufällig schon testen?

**Comment by novinet-dsteffen** [comment]
yes, funktioniert wunderbar

**Comment by eaCe** [comment]
@novinet-dsteffen super, danke. Dann werde ich das die Tage mal veröffentlichen.
