### ISSUE TITLE
Modul-Key statt Modul-ID verwenden

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/module_preview#8]
> Die Modul-ID gibt den Bildname vor (1.jpg, 2.jpg, etc.).

Würde man stattdessen / ergänzend den Modul-Key verwenden, könnte man die Bilder projektübergreifend benennen / ablegen.

**Comment by eaCe** [comment]
Lieber oder statt statt :) 
Dann kann man auch mischen, warum auch immer...

**Comment by eaCe** [comment]
Ich würde den Key nutzen, falls dieser vorhanden ist. Man muss keine Key nutzen oder auf älteren Versionen ist gar keiner verfügbar.

**Comment by eaCe** [comment]
@alxndr-w wenn du möchtest kannst du die aktuelle GH-Version probieren.

**Comment by eaCe** [comment]
https://github.com/FriendsOfREDAXO/module_preview/commit/38a070c47abaedbc15741ca501ccdade70b08a97
